before_script:
  - pwd
  - ruby -v
  - bundle install -j $(nproc)

stages:
  - rubocop
  - test

rubocop:
  stage: rubocop
  when: always
  script:
    - bin/rails rubocop

test:
  stage: test
  only:
    - master
  script:
    - bundle install -j $(nproc)
    - ln -s /home/gitlab-runner/shared/configs/as_projects/omni_engines/omni_region/database.yml ./test/dummy/config/database.yml
    - bin/rails db:drop RAILS_ENV=test
    - bin/rails db:create RAILS_ENV=test
    - bin/rails db:migrate RAILS_ENV=test
    - bin/rails test
