inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-erb
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - bin/bundle
    - db/schema.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Alias:
  EnforcedStyle: prefer_alias_method

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 10
  Exclude:
    - "db/migrate/*.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*.rake"
    - "config/environments/*.rb"
    - "test/**/*_test.rb"
    - "*.gemspec"
    - "config/routes.rb"
    - "Gemfile"
